### Задание 1

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,3,1], [6,8,11,10,7]]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

### Задание 2

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [5]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [6]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])
a_centered_sp

8.0

In [7]:
N = np.size(a_centered, axis = 0)
N

5

In [8]:
a_cov = a_centered_sp / (N - 1)
a_cov

2.0

### Задание 4

In [14]:
a_cov_alt = np.cov(a.T)
a_cov_alt[0,1]

2.0

In [16]:
a_cov == a_cov_alt[0,1]

True